export const watchList = [
    {title: 'ShadowHunters'},
    {title: 'Lucifer', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Westworld', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Vikings', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'The Gifted', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Star Trek Discovery', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Travelers', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'The Expanse', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Salvation', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'The Magicians', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Future Man', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'South Park', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'The Walking Dead', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'The Orville', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Timeless', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Black Mirror', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Marvels Runaways', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Arrow', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'DC\' Legends of Tomorrow', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'The Flash', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Supergirl', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'The Handmaid\'s Tale', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'The Good Place', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Doctor Who', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Elementary', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Lost In Space', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Final Space', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Daybreak', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'The Order', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'The 100', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'The Last Ship', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'The Purge', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Watchmen', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'See', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'His Dark Materials', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Roswell, New Mexico', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Into the Badlands', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Charmed', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Jumper', episode: '', season: '', year: '3000', description: 'movie', image: ''},
    // {title: 'Next Three Days', episode: '', season: '', year: '3000', description: 'movie', image: ''},
    // {title: 'Law Abiding Citizen', episode: '', season: '', year: '3000', description: 'movie', image: ''},
    // {title: '12 Monkeys', episode: '', season: '', year: '3000', description: 'movie', image: ''},
    // {title: 'Once Upon A Time', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Marvel\'s Agents of S.H.I.E.L.D', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Legion', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Defying Gravity', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Riverdale', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'iZombie', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Deus', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Black', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Ajin', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Jessica Jones', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'The Tomorrow People', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'StartUp', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Mars', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Dark', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'People of Earth', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Gravity Falls', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Atomic Blond', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Unbreakable', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Dark', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'The Missing', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Legion', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Luke Cage', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'The Punisher', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Emerald City', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'The Tomorrow People', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Continuum', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Children of the Machine', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Sense8', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Inner Dimension', episode: '', season: '', year: '3000', description: 'series', image: ''},
    // {title: 'Childhood\'s End', episode: '', season: '', year: '3000', description: 'series', image: ''},
];
